server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharing_car_test?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mybaits-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.flab.simplesharingcar.domain
