name: test-cicd

on:
  push:
    branches: [ "chore/add-ci-cd-pipeline" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # 체크아웃
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${secrets.DOCKER_USERNAME}
          password: ${secrets.DOCKER_PASSWORD}
      - name: build and release to DockerHub
        env:
          NAME: ${secrets.DOCKER_USERNAME}
          APP: simple-sharing-car-app
        run: |
          docker build -t $NAME/$APP -f ./Dockerfile .
          docker push $NAME/$APP:latest
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build the stack
        run: docker-compose up -d